/** 회원 */
create table member
(
    id                bigint generated by default as identity primary key,
    email             varchar(100) not null unique,
    username          varchar(50)  not null unique,
    password          varchar(255) not null,
    display_name      varchar(100) not null,
    profile_image_url varchar(500),
    provider          varchar(20),
    provider_id       varchar(100),
    created_at        timestamp(6) not null,
    updated_at        timestamp(6) not null
);

comment on column member.id is 'pk';
comment on column member.email is '이메일';
comment on column member.username is '사용자핸들';
comment on column member.password is '비밀번호';
comment on column member.display_name is '화면표시명';
comment on column member.profile_image_url is '프로필 이미지 URL';
comment on column member.provider_id is 'OAuth2 제공자 ID';
comment on column member.provider is 'OAuth2 제공자';
comment on column member.created_at is '생성일시';
comment on column member.updated_at is '수정일시';

CREATE INDEX idx_members_provider ON member (provider, provider_id);

---

/** 앨범 */
create table album
(
    id              bigint generated by default as identity primary key,
    member_id       bigint                                         not null,
    title           varchar(100)                                   not null,
    description     varchar(500),
    status          varchar(20) default 'DRAFT'::character varying not null,
    view_count      integer     default 0                          not null,
    cover_image_url varchar(500),
    deleted_at      timestamp(6),
    created_at      timestamp(6)                                   not null,
    updated_at      timestamp(6)                                   not null
);


comment on column album.id is 'pk';
comment on column album.member_id is '작성자 회원 pk';
comment on column album.title is '앨범 제목';
comment on column album.description is '앨범 설명';
comment on column album.status is '상태';
comment on column album.view_count is '조회수';
comment on column album.cover_image_url is '커버 이미지 URL';
comment on column album.deleted_at is '삭제일시';
comment on column album.created_at is '생성일시';
comment on column album.updated_at is '수정일시';

---

/** 사진 */
create table photo
(
    id              bigint generated by default as identity primary key,
    album_id        bigint            not null,
    title           varchar(100),
    description     varchar(500),
    thumbnail_url   varchar(500)      not null,
    image_url       varchar(500)      not null,
    image_name      varchar(255)      not null,
    image_size      bigint            not null,
    image_extension varchar(10)       not null,
    display_order   integer default 0 not null,
    width           integer           not null,
    height          integer           not null,
    camera_model    varchar(100),
    lens_model      varchar(100),
    iso             integer,
    aperture        varchar(10),
    shutter_speed   varchar(20),
    taken_at        date,
    created_at      timestamp(6)      not null,
    updated_at      timestamp(6)      not null
);

comment on column photo.id is 'pk';
comment on column photo.album_id is '앨범 pk';
comment on column photo.title is '제목';
comment on column photo.description is '설명';
comment on column photo.thumbnail_url is '썸네일 URL';
comment on column photo.image_url is '이미지 URL';
comment on column photo.image_name is '이미지 파일명';
comment on column photo.image_size is '이미지 파일 크기 (바이트)';
comment on column photo.image_extension is '이미지 확장자';
comment on column photo.display_order is '전시 순서';
comment on column photo.width is '이미지 가로 크기 (픽셀)';
comment on column photo.height is '이미지 세로 크기 (픽셀)';
comment on column photo.camera_model is '카메라 모델';
comment on column photo.lens_model is '렌즈 모델';
comment on column photo.iso is 'iso';
comment on column photo.aperture is '조리개';
comment on column photo.shutter_speed is '셔터스피드';
comment on column photo.taken_at is '촬영일자';
comment on column photo.created_at is '생성일시';
comment on column photo.updated_at is '수정일시';
