/** 회원 */
DROP TABLE IF EXISTS member;
create table member
(
    id                bigint generated by default as identity primary key,
    email             varchar(100)                                     not null unique,
    username          varchar(50) unique,
    password          varchar(255),
    display_name      varchar(100),
    profile_image_url varchar(500),
    provider          varchar(20),
    provider_id       varchar(100),
    status            varchar(20) default 'PENDING'::character varying not null,
    created_at        timestamp(6)                                     not null,
    updated_at        timestamp(6)                                     not null
);

comment on column member.id is 'pk';
comment on column member.email is '이메일';
comment on column member.username is '사용자핸들';
comment on column member.password is '비밀번호';
comment on column member.display_name is '화면표시명';
comment on column member.profile_image_url is '프로필 이미지 URL';
comment on column member.provider_id is 'OAuth2 제공자 ID';
comment on column member.provider is 'OAuth2 제공자';
comment on column member.status is '회원 상태 (PENDING: 추가정보입력대기, ACTIVE: 활성)';
comment on column member.created_at is '생성일시';
comment on column member.updated_at is '수정일시';

CREATE INDEX idx_members_provider ON member (provider, provider_id);

---

/** 앨범 */
DROP TABLE IF EXISTS album;
create table album
(
    id          bigint generated by default as identity primary key,
    member_id   bigint                                         not null,
    title       varchar(100)                                   not null,
    description varchar(500),
    status      varchar(20) default 'DRAFT'::character varying not null,
    view_count  integer     default 0                          not null,
    deleted_at  timestamp(6),
    created_at  timestamp(6)                                   not null,
    updated_at  timestamp(6)                                   not null,
    image_id    bigint
);


comment on column album.id is 'pk';
comment on column album.member_id is '작성자 회원 pk';
comment on column album.title is '앨범 제목';
comment on column album.description is '앨범 설명';
comment on column album.status is '상태';
comment on column album.view_count is '조회수';
comment on column album.deleted_at is '삭제일시';
comment on column album.created_at is '생성일시';
comment on column album.updated_at is '수정일시';
comment on column album.image_id is '커버 이미지 ID';

---

/** 사진 */
DROP TABLE IF EXISTS photo;
create table photo
(
    id            bigint generated by default as identity primary key,
    album_id      bigint            not null,
    title         varchar(100),
    description   varchar(500),
    display_order integer default 0 not null,
    created_at    timestamp(6)      not null,
    updated_at    timestamp(6)      not null,
    thumbnail_id  bigint            not null,
    image_id      bigint            not null
);

comment on column photo.id is 'pk';
comment on column photo.album_id is '앨범 pk';
comment on column photo.title is '제목';
comment on column photo.description is '설명';
comment on column photo.display_order is '전시 순서';
comment on column photo.created_at is '생성일시';
comment on column photo.updated_at is '수정일시';
comment on column photo.thumbnail_id is '썸네일 ID';
comment on column photo.image_id is '이미지 ID';

---

/** 리프레시 토큰 */
DROP TABLE IF EXISTS refresh_token;
create table refresh_token
(
    id         bigint generated by default as identity primary key,
    member_id  bigint       not null,
    token      varchar(500) not null unique,
    expires_at timestamp(6) not null,
    created_at timestamp(6) not null
);

comment on column refresh_token.id is 'pk';
comment on column refresh_token.member_id is '회원 pk';
comment on column refresh_token.token is '리프레시 토큰';
comment on column refresh_token.expires_at is '만료일시';
comment on column refresh_token.created_at is '생성일시';

CREATE INDEX idx_refresh_token_member_id ON refresh_token (member_id);

---

/** 업로드 파일 */
DROP TABLE IF EXISTS upload_file;
create table upload_file
(
    id               bigint generated by default as identity primary key,
    url              varchar(500)                                      not null,
    origin_file_name varchar(255)                                      not null,
    save_file_name   varchar(255)                                      not null,
    size             bigint                                            not null,
    extension        varchar(10)                                       not null,
    width            integer,
    height           integer,
    camera_model     varchar(100),
    lens_model       varchar(100),
    iso              integer,
    aperture         varchar(10),
    shutter_speed    varchar(20),
    taken_at         date,
    created_at       timestamp(6)                                      not null,
    status           varchar(20) default 'UPLOADED'::character varying not null
);

comment on column upload_file.id is 'pk';
comment on column upload_file.url is '파일 URL';
comment on column upload_file.origin_file_name is '원본 파일 이름';
comment on column upload_file.save_file_name is '저장된 파일 이름';
comment on column upload_file.size is '파일 크기 (바이트)';
comment on column upload_file.extension is '파일 확장자';
comment on column upload_file.width is '이미지 가로 크기 (픽셀)';
comment on column upload_file.height is '이미지 세로 크기 (픽셀)';
comment on column upload_file.camera_model is '카메라 모델';
comment on column upload_file.lens_model is '렌즈 모델';
comment on column upload_file.iso is 'iso';
comment on column upload_file.aperture is '조리개';
comment on column upload_file.shutter_speed is '셔터스피드';
comment on column upload_file.taken_at is '촬영일자';
comment on column upload_file.created_at is '생성일시';
comment on column upload_file.status is '상태 (UPLOADED: 업로드, CONFIRMED: 확정)';
